data:
  FUNCTIONS_WORKER_RUNTIME: bm9kZQ==
  AzureWebJobsStorage: ""
apiVersion: v1
kind: Secret
metadata:
  name: hello-example
---
data:
  host.master: dmNzc1M2YWd4R2hydG1TQnVSYy1kUkVhQlo3Z3UzQ1hkNkV0RGVRc2d2eVBBekZ1SGZaeDVBPT0=
  host.function.default: WWVvT3FQLU1ZU28wWi1LZjZ2Y2JibGVONVNvNGZneGhndklDOEVJMEFhdGNBekZ1bldGSlN3PT0=
  host.systemKey.default: MDNQQklCaDNnNV9NM1dIZEZlaW5aQ1FuakVndHBnWEZ6QmRqRnMwMnBCcmRBekZ1ZmEzZmNnPT0=
  functions.httpexample.default: R2sxbUtTd2gwLWZOazBrOVk2bG56cFhOVmJmS1c2d1FYZ3dvbzJKZGpuSXRBekZ1TVdhaGpnPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-hello-example
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-example-function-keys-identity-svc-act
---
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configMaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
  - kind: ServiceAccount
    name: hello-example-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-example-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: hello-example-http
spec:
  selector:
    app: hello-example-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-example-http
  labels:
    app: hello-example-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-example-http
  template:
    metadata:
      labels:
        app: hello-example-http
    spec:
      containers:
        - name: hello-example-http
          image: anbofunacr.azurecr.io/anbofun-fun:latest
          ports:
            - containerPort: 80
          env:
            - name: AzureFunctionsJobHost__functions__0
              value: HttpExample
            - name: AzureWebJobsSecretStorageType
              value: kubernetes
            - name: AzureWebJobsKubernetesSecretName
              value: secrets/func-keys-kube-secret-hello-example
          envFrom:
            - secretRef:
                name: hello-example
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 240
            httpGet:
              path: /
              port: 80
              scheme: HTTP
          startupProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 240
            httpGet:
              path: /
              port: 80
              scheme: HTTP
      serviceAccountName: hello-example-function-keys-identity-svc-act
---